/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaterialRouteImport } from './routes/material'

const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/material': typeof MaterialRoute
}
export interface FileRoutesByTo {
  '/material': typeof MaterialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/material': typeof MaterialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/material'
  fileRoutesByTo: FileRoutesByTo
  to: '/material'
  id: '__root__' | '/material'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MaterialRoute: typeof MaterialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MaterialRoute: MaterialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
